apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "awx.fullname" . }}-application-credentials
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "awx.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  credentials_py : |
    DATABASES = {
        'default': {
            'ATOMIC_REQUESTS': True,
            'ENGINE': 'awx.main.db.profiled_pg',
            'NAME': "{{ .Values.postgres.database }}",
            'USER': "{{ .Values.postgres.username }}",
            'PASSWORD': "{{ .Values.postgres.password }}",
            'HOST': "{{ .Values.postgres.hostname }}",
            'PORT': "{{ .Values.postgres.port }}",
        }
    }
    BROKER_URL = 'amqp://{}:{}@{}:{}/{}'.format(
        "{{ .Values.rabbitmq.username }}",
        "{{ .Values.rabbitmq.password }}",
        "localhost",
        "5672",
        "awx")
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'asgi_amqp.AMQPChannelLayer',
                    'ROUTING': 'awx.main.routing.channel_routing',
                    'CONFIG': {'url': BROKER_URL}}
    }
  environment_sh: |
    DATABASE_USER={{ .Values.postgres.username }}
    DATABASE_NAME={{ .Values.postgres.database }}
    DATABASE_HOST={{ .Values.postgres.hostname }}
    DATABASE_PORT={{ .Values.postgres.port }}
    DATABASE_PASSWORD={{ .Values.postgres.password }}
    MEMCACHED_HOST={{ .Values.memcached.hostname }}
    MEMCACHED_PORT={{ .Values.memcached.port }}
    RABBITMQ_HOST={{ .Values.rabbitmq.hostname }}
    RABBITMQ_PORT={{ .Values.rabbitmq.port }}
    AWX_ADMIN_USER={{ .Values.admin_user }}
    AWX_ADMIN_PASSWORD={{ .Values.admin_password }}
