kind: Service
apiVersion: v1
metadata:
  name: {{ include "awx.fullname" . }}-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "awx.name" . }}
{{ include "awx.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
  selector:
    app: {{ include "awx.name" . }}
