kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name:  {{ include "awx.fullname" . }}-endpoint-reader
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "awx.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
