kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "awx.fullname" . }}-endpoint-reader
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "awx.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "awx.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "awx.fullname" . }}-endpoint-reader
