apiVersion: v1
kind: Secret
metadata:
  name: {{ include "awx.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "awx.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  secret_key: {{ .Values.secret_key | b64enc | quote }}
  admin_password: {{ .Values.admin_password | b64enc | quote }}
  pg_password:  {{ .Values.postgres.password | b64enc | quote }}
  rabbitmq_password: {{ .Values.rabbitmq.password | b64enc | quote }}
  rabbitmq_erlang_cookie: {{ .Values.rabbitmq.erlang_cookie | b64enc | quote }}
