apiVersion: v1
kind: Service
metadata:
  name: {{ include "awx.fullname" . }}-web-svc
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "awx.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8052
  selector:
    name: {{ include "awx.name" . }}-web-deploy
